rm -rf   ../custom/themes/example.zsh-theme
	rm -rf   3den.zsh-theme
	rm -rf   Soliah.zsh-theme
	rm -rf   alanpeabody.zsh-theme
	rm -rf   apple.zsh-theme
	rm -rf   arrow.zsh-theme
	rm -rf   awesomepanda.zsh-theme
	rm -rf   bira.zsh-theme
	rm -rf   blinks.zsh-theme
	rm -rf   bureau.zsh-theme
	rm -rf   candy-kingdom.zsh-theme
	rm -rf   candy.zsh-theme
	rm -rf   clean.zsh-theme
	rm -rf   cloud.zsh-theme
	rm -rf   crcandy.zsh-theme
	rm -rf   cypher.zsh-theme
	rm -rf   dallas.zsh-theme
	rm -rf   darkblood.zsh-theme
	rm -rf   daveverwer.zsh-theme
	rm -rf   dieter.zsh-theme
	rm -rf   dogenpunk.zsh-theme
	rm -rf   dst.zsh-theme
	rm -rf   dstufft.zsh-theme
	rm -rf   duellj.zsh-theme
	rm -rf   eastwood.zsh-theme
	rm -rf   edvardm.zsh-theme
	rm -rf   emotty.zsh-theme
	rm -rf   evan.zsh-theme
	rm -rf   fino-time.zsh-theme
	rm -rf   fino.zsh-theme
	rm -rf   fishy.zsh-theme
	rm -rf   fox.zsh-theme
	rm -rf   frisk.zsh-theme
	rm -rf   frontcube.zsh-theme
	rm -rf   funky.zsh-theme
	rm -rf   fwalch.zsh-theme
	rm -rf   gallifrey.zsh-theme
	rm -rf   gallois.zsh-theme
	rm -rf   garyblessington.zsh-theme
	rm -rf   geoffgarside.zsh-theme
	rm -rf   gianu.zsh-theme
	rm -rf   gozilla.zsh-theme
	rm -rf   humza.zsh-theme
	rm -rf   imajes.zsh-theme
	rm -rf   intheloop.zsh-theme
	rm -rf   itchy.zsh-theme
	rm -rf   jbergantine.zsh-theme
	rm -rf   jispwoso.zsh-theme
	rm -rf   jonathan.zsh-theme
	rm -rf   josh.zsh-theme
	rm -rf   jreese.zsh-theme
	rm -rf   jtriley.zsh-theme
	rm -rf   juanghurtado.zsh-theme
	rm -rf   junkfood.zsh-theme
	rm -rf   kardan.zsh-theme
	rm -rf   kennethreitz.zsh-theme
	rm -rf   kiwi.zsh-theme
	rm -rf   kolo.zsh-theme
	rm -rf   lambda.zsh-theme
	rm -rf   linuxonly.zsh-theme
	rm -rf   mgutz.zsh-theme
	rm -rf   mh.zsh-theme
	rm -rf   michelebologna.zsh-theme
	rm -rf   mikeh.zsh-theme
	rm -rf   miloshadzic.zsh-theme
	rm -rf   minimal.zsh-theme
	rm -rf   mira.zsh-theme
	rm -rf   mortalscumbag.zsh-theme
	rm -rf   mrtazz.zsh-theme
	rm -rf   murilasso.zsh-theme
	rm -rf   nanotech.zsh-theme
	rm -rf   nebirhos.zsh-theme
	rm -rf   nicoulaj.zsh-theme
	rm -rf   norm.zsh-theme
	rm -rf   peepcode.zsh-theme
	rm -rf   philips.zsh-theme
	rm -rf   pmcgee.zsh-theme
	rm -rf   pygmalion-virtualenv.zsh-theme
	rm -rf   refined.zsh-theme
	rm -rf   rgm.zsh-theme
	rm -rf   rixius.zsh-theme
	rm -rf   rkj-repos.zsh-theme
	rm -rf   rkj.zsh-theme
	rm -rf   robbyrussell.zsh-theme
	rm -rf   sammy.zsh-theme
	rm -rf   simonoff.zsh-theme
	rm -rf   skaro.zsh-theme
	rm -rf   smt.zsh-theme
	rm -rf   sonicradish.zsh-theme
	rm -rf   sorin.zsh-theme
	rm -rf   sporty_256.zsh-theme
	rm -rf   steeef.zsh-theme
	rm -rf   strug.zsh-theme
	rm -rf   sunaku.zsh-theme
	rm -rf   suvash.zsh-theme
	rm -rf   takashiyoshida.zsh-theme
	rm -rf   terminalparty.zsh-theme
	rm -rf   theunraveler.zsh-theme
	rm -rf   tonotdo.zsh-theme
	rm -rf   trapd00r.zsh-theme
	rm -rf   wedisagree.zsh-theme
	rm -rf   wezm+.zsh-theme
	rm -rf   wezm.zsh-theme
	rm -rf   wuffers.zsh-theme
	rm -rf   xiong-chiamiov-plus.zsh-theme
	rm -rf   xiong-chiamiov.zsh-theme
	rm -rf   zhann.zsh-theme
     rm -rf   ys.zsh-theme